import {ReactNode} from 'react';
import {Inter} from 'next/font/google';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });


export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function Layout(props: { children: ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                {props.children}
            </body>
        </html>
    )
}
